### PR TITLE
add: txt output format for pgfplots/gnuplot/etc

### PR DESCRIPTION
**Pull request by timovanopstal**
I'd like to have this output format added.
ps. badger is great!

### CODE REVIEW

**Comment by timovanopstal** [comment]
don't pull yet, found an issue

**Comment by timovanopstal** [comment]
there. that's better.

**Comment by timovanopstal** [comment]
Ready for a pull now. There's a minimal example of using this output data in pgfplots [here](http://tex.stackexchange.com/questions/342473/applying-multiple-filters-to-plot-data)

**Comment by TheBB** [comment]
Thanks!

**Pull request closed without merging**
