### PR TITLE
[WIP] Improved capturing support

### PR DESCRIPTION
**Pull request by TheBB**
This PR resolves the following issues:

- #1 
- #9
- #13 (partially)

### CODE REVIEW

**Comment by TheBB** [comment]
@akva2 @timovanopstal Here's an example of something that is possible using this branch, together with a geometry generation script and ifem-inspect.

I think I like it a lot. I haven't updated the tests though so I won't merge until that happens.

```yaml
files:
  - cracks.py
templates:
  - cracks.xinp
dependencies:
  frac_half_length: 250
  frac_width: 2
  dx: 150
  dy: 200
  dt: 300
  endtime: 1800
  stride: 1
  ymod: 45e9  # Young's modulus
  prat: 0.25  # Poisson ratio
commands:
  # Generate the geometry
  - cmd: >-
      python cracks.py
      frac_half_length={{frac_half_length}}
      frac_width={{frac_width}}
      dx={{dx}} dy={{dy}}
      n_frac=1 jp=1.9 da=0.3 infl=40 scl_frac=4 n_int=30 a_ext=1.14 n_ext=18 ampl=4
    stdout:
      - !!str 'nelems = (?P<nelems>[^\s]+)'
  # Perform simulation
  - cmd: >-
      /home/eivindf/work/IFEM/Apps/bld-sr/bin/PoroElasticity
      cracks.xinp -2D -mixed -vtf 1 -hdf5 cracks.hdf5
    stdout:
      - !!str 'Total time\s+\|\s+(?P<cputime>[^\s]+)\s+\|\s+(?P<walltime>[^\s]+)'
  # Plot stress
  - cmd: >-
      ifem-inspect plot Displacement -p 12 13 -u 41 41 -N500 -Hy -s{{stride}}
      --interpret stress_yy --title sigma_yy --save stress_yy.png
      --ymod {{ymod}} --prat {{prat}}
    files:
      - stress_yy.png
types:
  nelems: int
  cputime: float
  walltime: float
```

**Comment by timovanopstal** [comment]
Like it a lot too! Can commands also be parameter-dependent? You used dependencies in this e.g. That would save me from invoking badger from a bash script which takes care of changing commands and input files, which is my current mode of operation ;-)

**Comment by TheBB** [comment]
Yes, essentially everything is a template: the list of files, the list of templates, even the regular expressions (although I still haven't seen *that* being useful).

**Comment by timovanopstal** [comment]
Useful for making those regexps even more unreadable. Otherwise, I can't think of a situation either, good to have it anyways. For Skjervald (He was on about the 'uventede framtiden' right?)

**Pull request merged**
